<a href="https://colab.research.google.com/github/gaddammansi/FMML_Project-and-Labs-/blob/main/Basics_of_Python_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
#Question 0:
#write down 3-5 methods applicable to each data type. (Hint: extend, reverse, etc.
#STRING
#---------------
#upper() method:-
#Converts a string into upper case
#example:-
s = "Hello everyone"
print(s.upper())
#endswith() method:-
#Returns true if the string ends with the specified value
#example:-
s = "Hello everyone"
print(s.endswith("e"))
#isupper() method:-
#Returns True if all characters in the string are upper case
#example:-
s = "HELLO EVERYONe"
print(s.isupper())
#--------------------------------------------------------------------------------
#LIST
#append() method:-
#Adds an element at the end of the list
#example:-
s = ['nightingale', 'Cuckoo', 'Eagle']
s.append('Swan')
print(s)
#reverse() method:-
#Reverses the order of the list
#example:-
s = ['nightingale', 'Cuckoo', 'Eagle']
s.reverse()
print(s)
#index() method:-
#Returns the index of the first element with the specified value
#example:-
s = ['nightingale', 'Cuckoo', 'Eagle']
print(s.index("Eagle"))
#--------------------------------------------------------------------------------
#TUPLE
#-----------
#index() method:-
#Searches the tuple for a specified value and returns the position of where it was found
#example:-
s = (1, 2, 7, 5, 7, 9, 3, 6, 4, 8)
print(s.index(5))
#count() method:-
#Returns the number of times a specified value occurs in a tuple
#example:-
s = (1, 2, 7, 5, 7, 5, 3, 6, 5, 8)
print(s.count(5))
#--------------------------------------------------------------------------------
#SET
#-----------
#intersection() method:-
#Returns a set, that is the intersection of two or more sets
#example:-
s = {'nightingale', 'Cuckoo', 'Eagle'}
t = {'apricot', 'litchi', 'guava'}
w = s.intersection(t)
print(w)
#clear() method:-
#Removes all the elements from the set
#example:-
t = {'apricot', 'litchi', 'guava'}
print(t.clear())
#remove() method:-
#Removes the specified element
#example:-
s = {'nightingale', 'Cuckoo', 'Eagle'}
s.remove('Eagle')
print(s)
#--------------------------------------------------------------------------------
#DICTIONARY
#keys() methos:-
#Returns a list containing the dictionary's keys
#example:-
s = {'place': 'HYD','state': 'Telangana','pincode': 500091}
print(s.keys())
#clear() method:-
#Removes all the elements from the dictionary
#example:-
s = {'place': 'HYD','state': 'Telangana','pincode': 500091}
print(s.clear())
#pop() method:-
#Removes the element with the specified key
#example:-
s = {'place': 'HYD','state': 'Telangana','pincode': 500091}
s.pop('state')
print(s)
#------------------------------------------------------------------------------------------------------------------------------------------
#Question 1 :
#Define a function, which takes in two strings A and B. Reverses the first string A, adds it to B, and returns the final string.
def reverse_and_add_strings(A, B):
    reversestring_A = A[::-1] # Reverse string A
    result =  reversestring_A + B # Concatenation of the reversed string A with the string B

    return result # Returning the result

string_A = "Hey"
string_B = "Mansi"
Final_String = reverse_and_add_strings(string_A, string_B) # The final string
print(Final_String)
#------------------------------------------------------------------------------------------------------------------------------------------
#Question 2 :
#Given a list having Names, work_hours, and gender, Write a function to print name of the female worker that worked the most hours. Also how much do should she be paid if the pay is $ 20 per hour.
#work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
def calculate_pay(work_hours):
    max_hours = 0
    female_worker = None

    for name, hours, gender in work_hours:
        if gender == 'F' and hours > max_hours:
            max_hours = hours
            female_worker = name

    if female_worker is not None:
        payment = max_hours * 20
        print(f"The female worker who worked the most hours is {female_worker}")
        print(f"The amount she should be paid is ${payment}")
    else:
        print("No female workers found in the list.")

workhours = [('Abby', 100, 'F'), ('Billy', 400, 'M'), ('Cassie', 800, 'F'), ('Maggi', 600, 'F'),('Alex', 500, 'M'), ('Raj', 225, 'M'), ('Penny', 920, 'F'), ('Ben', 300, 'M')]

calculate_pay(workhours)
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Question 3 :
#a)Create a 5x5 matrix of the following form,
#[[1,1]
#[2,2]]i.e. each row is increasing and has repetive elements.

import numpy as np
base_matrix = np.array([[1, 1], [2, 2]])
horizontal_stack = np.hstack([base_matrix] * 3)
vertical_stack = np.vstack([horizontal_stack] * 3)
resultmatrix = vertical_stack[:5, :5]
print(resultmatrix)

#-------------------------------------------------------------------------------

#b) find dot product of the matrix with any matrix.

import numpy as np

A = np.array([[1, 2], [3, 4]])  # Defining matrix A
B = np.array([[5, 1], [2, 8]])  # Defining matrix B

if A.shape[1] == B.shape[0]: # Checking if the dimensions are compatible for multiplication
    C = np.dot(A, B)  # Computing the dot product of two matrices
    print("Matrix C (Dot Product of A and B):\n", C)
else:
    print("Matrix dimensions are not compatible for dot product.")
#------------------------------------------------------------------------------------------------------------------------------------------------------









HELLO EVERYONE
True
False
['nightingale', 'Cuckoo', 'Eagle', 'Swan']
['Eagle', 'Cuckoo', 'nightingale']
2
3
3
set()
None
{'Cuckoo', 'nightingale'}
dict_keys(['place', 'state', 'pincode'])
None
{'place': 'HYD', 'pincode': 500091}
yeHMansi
The female worker who worked the most hours is Penny
The amount she should be paid is $18400
[[1 1 1 1 1]
 [2 2 2 2 2]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [1 1 1 1 1]]
Matrix C (Dot Product of A and B):
 [[ 9 17]
 [23 35]]
